#!/usr/bin/bash
set -e

farm_name=$(git config --get remote.origin.url | xargs basename)
find . -maxdepth 1 -type d ! -name "." ! -name ".git" -printf "%P\n" | xargs -L1 -I dir stow dir

if [[ $? == 0 ]]; then
    echo "Created symlink farm for $farm_name."
fi
