-- vim.cmd("filetype off")

vim.o.autoindent = true
vim.o.background = "dark"
vim.o.backspace = "indent,eol,start"
vim.o.backup = false
vim.o.breakindent = true
-- vim.o.clipboard = "unnamedplus"
vim.o.cmdheight = 2
vim.o.complete = ".,w,b,u,t,i"
vim.o.completeopt = "menuone,noinsert,noselect"
vim.o.confirm = true
vim.o.encoding = "utf-8" vim.o.hidden = true
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.inccommand = "nosplit"
vim.o.incsearch = true
vim.o.infercase = true
vim.o.lazyredraw = false
vim.o.listchars = "tab:▸ ,eol:¬,trail:•,extends:»,precedes:«,tab:| ,trail:·"
vim.o.matchtime = 2
vim.o.modeline = false
vim.o.mouse = "a"
vim.o.pumheight = 15
vim.o.shortmess = vim.o.shortmess .. "c"
vim.o.showbreak = "+++ "
vim.o.showmatch = true
vim.o.showmatch = true
vim.o.showmode = true
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.termguicolors = true
vim.o.timeout = false
vim.o.timeoutlen = 100
vim.o.ttimeout = true
vim.o.ttimeoutlen = 100
vim.o.updatetime = 300
vim.o.wildmenu = true
vim.o.wildmode = "longest,list,full"
vim.o.wrapscan = true
vim.o.writebackup = false
vim.wo.cursorline = false
vim.wo.list = true
vim.wo.number = true
vim.wo.numberwidth = 5
vim.wo.relativenumber = true
vim.wo.signcolumn = "number"
vim.bo.expandtab = true
vim.bo.shiftwidth = 4
vim.bo.softtabstop = 4
vim.bo.swapfile = false
vim.bo.tabstop = 4
vim.o.history =  100
vim.o.shada = "!,'30,<50,s50,h"
