local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {'SidOfc/mkdx', ft = {"markdown", "md"}},
  {'f-person/git-blame.nvim', cmd = 'GitBlameToggle'},
  {'TimUntersberger/neogit', cmd = "Neogit", config = function() require("plugins.my_neogit") end},
  {'elm-tooling/elm-vim', ft = {'elm'}},
  -- {'danymat/neogen', ft = {"go", "python", "rust"}, config = function() require('plugins.my_neogen') end},
  {'godlygeek/tabular', cmd = "Tabularize"},
  {'hrsh7th/nvim-cmp', ft = {"elm", "go", "python", "rust"}, config = function() require("plugins.my_nvim-cmp") end},
  {'hrsh7th/cmp-buffer', ft = {"elm", "go", "python", "rust"}},
  {'hrsh7th/cmp-cmdline', ft = {"elm", "go", "python", "rust"}},
  {'hrsh7th/cmp-nvim-lsp', ft = {"elm", "go", "python", "rust"}},
  {'hrsh7th/cmp-path', ft = {"elm", "go", "python", "rust"}},
  {'j-hui/fidget.nvim', ft = {"elm", "go", "python", "rust"}, config = function() require("plugins.my_fidget") end},
  {'jbyuki/venn.nvim', cmd = "VBox"},
  {'junegunn/vim-peekaboo'},
  -- {'karb94/neoscroll.nvim', config = function() require("plugins.my_neoscroll") end},
  {'lewis6991/gitsigns.nvim', config = function() require('gitsigns').setup() end},
  {'moll/vim-bbye'},
  -- {'TimUntersberger/neofs', config = function() require("plugins.my_neofs") end},
  {'neovim/nvim-lspconfig', ft = {"elm", "go", "python", "rust"}, config = function() require("plugins.my_lsp") end},
  {'numToStr/Comment.nvim', config = function() require("plugins.my_comment-nvim") end},
  {'nvim-treesitter/nvim-treesitter', ft = {"elm", "go", "python", "rust"}, config = function() require("plugins.my_treesitter") end},
  {'onsails/lspkind-nvim'},
  {'pwntester/octo.nvim', cmd = {'Octo'}, config = function() require("plugins.my_octo") end},
  {'rodjek/vim-puppet', ft = {'puppet', 'epuppet'}},
  {'romgrk/nvim-treesitter-context'},
  {'rust-lang/rust.vim', ft = {'rust'}},
  {'sindrets/diffview.nvim', dependencies = 'nvim-lua/plenary.nvim', config = function() require("plugins.my_diffview") end},
  {'skywind3000/asyncrun.vim', cmd = {"AsyncRun", "AsyncStop"}},
  {'skywind3000/asynctasks.vim', cmd = {"AsyncTask", "AsyncTaskEdit", "AsyncTaskMacro", "AsyncTaskList", "AsyncTaskProfile"}, config = function() require("plugins.my_async") end},
  {'togglebyte/togglerust', ft = {'rust'}},
  {'tpope/vim-fugitive', cmd = {'Commits'}},
  {'tpope/vim-repeat', event = "InsertEnter"},
  {'tpope/vim-surround', event = "InsertEnter"},
  {'vimwiki/vimwiki', cmd = {'VimWikiIndex'}, config = function() require("plugins.my_vimwiki") end},
  -- {'numToStr/FTerm.nvim', config = function() require("plugins.my_fterm") end},
  {'windwp/nvim-autopairs', event = "InsertEnter", config = function() require("plugins.my_autopairs") end},
  -- {'junegunn/fzf'},
  -- {'junegunn/fzf.vim'},
  {'nvim-lua/plenary.nvim'},
  {'imsnif/kdl.vim'},
  {'nathanalderson/yang.vim'},
  {'folke/tokyonight.nvim'},
  {'gfanto/fzf-lsp.nvim', ft = {'go', 'python', 'rust'}, dependencies = "plenary.nvim"},
  {'weilbith/nvim-code-action-menu', ft = {'go', 'python', 'rust'}, cmd = 'CodeActionMenu'},
  {'kosayoda/nvim-lightbulb', dependencies = 'antoinemadec/FixCursorHold.nvim', config = function() require("nvim-lightbulb").setup({autocmd = {enabled = true}}) end},
  {"nvim-neorg/neorg", dependencies = "plenary.nvim", config = function() require('plugins.my_neorg') end},
  {"folke/zen-mode.nvim"},
  {"stevearc/oil.nvim", config = function() require('plugins.my_oil') end},
  {"nvim-telescope/telescope.nvim", tag = "0.1.1", dependencies = { "nvim-lua/plenary.nvim" }, config = function() require('plugins.my_telescope') end},
  {"junegunn/vim-fnr", dependencies = {"junegunn/vim-pseudocl"}},
})
